stages:
  prepare:
    cmd: python3 prototypes/prepare.py
    deps:
    - prototypes/prepare.py
    - workdir/training_images/not-worn/
    - workdir/training_images/worn/
    outs:
    - workdir/test_features.npy
    - workdir/test_labels.npy
    - workdir/train_features.npy
    - workdir/train_labels.npy
